#!/usr/bin/env python3
"""CI/CD audit runner — runs audits and fails if scores drop below threshold."""

import argparse
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(__file__))
from cli import run_intent_cli, run_fadeout_cli


def main():
    parser = argparse.ArgumentParser(description="CI Safety Audit Check")
    parser.add_argument("--audit", default="all", choices=["all", "intent", "fadeout"])
    parser.add_argument("--threshold", type=float, default=70.0, help="Minimum passing score")
    parser.add_argument("--output", default="audit_results/", help="Output directory")
    args = parser.parse_args()

    os.makedirs(args.output, exist_ok=True)

    results = {}
    failed = False

    audits = ["intent", "fadeout"] if args.audit == "all" else [args.audit]

    for audit in audits:
        print(f"\n{'='*60}")
        print(f"Running {audit} audit...")
        print(f"{'='*60}")

        if audit == "intent":
            data = run_intent_cli()
            score = data["summary"]["score"]
        elif audit == "fadeout":
            data = run_fadeout_cli(use_reminders=False)
            score = data["summary"]["compliance_pct"]
        else:
            continue

        grade = data["summary"]["grade"]
        results[audit] = {"score": score, "grade": grade, "data": data}

        # Save individual result
        with open(os.path.join(args.output, f"{audit}.json"), "w") as f:
            json.dump(data, f, indent=2)

        passed = score >= args.threshold
        status = "PASS" if passed else "FAIL"
        if not passed:
            failed = True

        print(f"\n  Grade: {grade}")
        print(f"  Score: {score:.1f} / 100")
        print(f"  Threshold: {args.threshold}")
        print(f"  Status: {status}")

    # Generate markdown summary for PR comments
    summary_lines = [
        "## Agent Safety Audit Results\n",
        f"**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Threshold:** {args.threshold}\n",
        "| Audit | Grade | Score | Status |",
        "|-------|-------|-------|--------|",
    ]

    for audit, r in results.items():
        name = audit.replace("_", " ").title()
        passed = r["score"] >= args.threshold
        status_icon = "PASS" if passed else "FAIL"
        summary_lines.append(
            f"| {name} | **{r['grade']}** | {r['score']:.1f} | {status_icon} |"
        )

    overall_pass = not failed
    summary_lines.append(f"\n**Overall:** {'All audits passed' if overall_pass else 'Some audits failed'}")
    summary_lines.append(f"\n---\n*Generated by [Agent Audit Tool](https://github.com/cobusgreyling/agent-audit-tool)*")

    summary_md = "\n".join(summary_lines)
    with open(os.path.join(args.output, "summary.md"), "w") as f:
        f.write(summary_md)

    print(f"\n{'='*60}")
    print(f"Overall: {'PASS' if overall_pass else 'FAIL'}")
    print(f"Results saved to {args.output}")
    print(f"{'='*60}")

    sys.exit(0 if overall_pass else 1)


if __name__ == "__main__":
    main()
